import TopLeftImg from "./TopLeftImg"
import Nav from "./Nav"
import Header from "./Header"
import Circles from "./Circles"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1", // <-- here
}

const Layout = ({ children, fontSora }) => {
  return (
    <>
      <div className={`page h-dvh bg-site bg-cover bg-no-repeat text-white ${fontSora.variable}`}>
        <div className="flex h-full flex-col justify-between bg-gradient-to-r from-primary/10 via-black/30 to-black/10">
          <TopLeftImg />
          <Header />
          {children}
          <Nav />
          <Circles />
        </div>
      </div>
    </>
  )
}

export default Layout
